#ifndef TIMER_CONFIG_H_
#define TIMER_CONFIG_H_

#define F_CPU 8000000UL


#define TIMER0_enable

#define TIMER0_INTERRUPT_ENABLE TOV0
#define TIMER0_WAVEFORM_GENERATION_MODE NORMAL
#define TIMER0_PRESCALER PRESCALER_64
#define TIMER0_COMPARE_OUTPUT_MODE NORMAL_PORT_OPERATION
//TIMER1 

#define TIMER1_enable

#define TIMER1_INTERRUPT_ENABLE NO_INTERRUTP
#define TIMER1_WAVEFORM_GENERATION_MODE NORMAL
#define TIMER1_PRESCALER PRESCALER_8
#define TIMER1_COMPARE_OUTPUT_MODE NORMAL_PORT_OPERATION
#define Channel_A 
//#define Channel_B 




//TIMER2
#define TIMER2_enable
#define TIMER2_INTERRUPT_ENABLE NO_INTERRUTP
#define TIMER2_WAVEFORM_GENERATION_MODE NORMAL
#define TIMER2_PRESCALER PRESCALER_8
#define TIMER2_COMPARE_OUTPUT_MODE NORMAL_PORT_OPERATION


#endif /* TIMER_CONFIG_H_ */
