#ifndef ADC_CONFIG_H_
#define ADC_CONFIG_H_

#define ADC_REF_VOLTAGE AREF

#define ADC_ADJUSTMENT LEFT_ADJUSTMENT

#define ADC_PRESCALER DIVISION_FACTOR_128

#define ADC_TIMEOUT  50000

#endif /* ADC_CONFIG_H_ */
